### ISSUE TITLE
(3) many-to-many relationships in Rails

### ISSUE THREAD

**Issue by erskin19** [erskin19/tc359_rails_final#2]
Requirements: You've successfully implemented a many-to-many relationship between two models in your app, which is reflected in additional functionality available to users

**Comment by erskin19** [comment]
@chrisvfritz Did I meet the requirements? https://pure-mountain-5478.herokuapp.com/

**Comment by chrisvfritz** [comment]
This looks really good. Nice job tackling the toughest skill! It looks like you've also created a scaffold for commenters, but decided to just use users instead (which you're right is the way to go). Since we're no longer using that, it's best to clean up those files. This can be done quickly with:

```
rails destroy scaffold commenters
```

My other comments below aren't anything you have to update, but rather notes that you might find useful regarding associations like this.

### Using custom names for associations

In these cases, you often might want to use a users model for an association, but don't want to call the association user(s) in that context. In this case, it looks like you created the commenters scaffold because you wanted pets to have _commenters_. That makes a lot of sense. In the future, we might even want pets to have many different associations with the users table. For example, a pet might have many _commenters_, have many _owners_, and belong to a _vet_. 

In cases like this, there are some extra parameters we can use when defining our relationships. [This page](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html) talks about all of them in detail, but here's an example of how we might customize our names for these associations:

``` ruby
# app/models/user.rb
has_many :comments
has_many :commented_pets, through: :comments, class_name: :Pet, source: :pet
```

``` ruby
# app/models/pet.rb
has_many :comments
has_many :commenters, through: :comments, class_name: :User, source: :author
```

``` ruby
# app/models/comment.rb
belongs_to :author, class_name: :User, foreign_key: :user_id
belongs_to :pet
```

### Deleting comments when a pet is deleted

When a user or pet is deleted from the system, you might also want to automatically delete all the comments that were on that pet. This can be done by adding `dependent: :destroy` to the comments, assocation. For example:

``` ruby
# app/models/user.rb
has_many :comments, dependent: :destroy
has_many :commented_pets, through: :comments, class_name: :Pet, source: :pet
```

``` ruby
# app/models/pet.rb
has_many :comments, dependent: :destroy
has_many :commenters, through: :comments, class_name: :User, source: :author
```

**Comment by erskin19** [comment]
I deleted the scaffold and removed it from git. Thanks for the notes!

**Comment by chrisvfritz** [comment]
:+1: Looks great!
